
#include "/Plugin/Ue5MMDTools/TShaderFunctionLibrary/ColorAdjustment.usf"

// input
// float4 base_color_map_value
// float3 skin_color

struct TMMDShaderPBRSkin
{

    float4 OutputColor(FMaterialPixelParameters material_parameters, float4 base_color_map_value, float3 skin_color)
    {
///parameter input
        float3 main_light_dir = normalize(ResolvedView.AtmosphereLightDirection[0].xyz);
        float3 main_light_color = ResolvedView.AtmosphereLightIlluminanceOnGroundPostTransmittance[0].rgb;

        // float3 main_light_tint = NormalizeLightColor(main_light_color);
        // float main_light_strength = GetLightStrength(main_light_color);

        float3 view_dir = normalize(material_parameters.CameraVector);
        float3 pixel_normal = normalize(material_parameters.WorldNormal * material_parameters.TwoSidedSign);
        float3 vertex_normal = normalize(material_parameters.TangentToWorld[2] * material_parameters.TwoSidedSign);

        // float3 world_pos = GetTranslatedWorldPosition(material_parameters);
        // float3 object_pos = GetObjectTranslatedWorldPosition(material_parameters);
        // float3 object_radial_normal = normalize(world_pos - object_pos);
///final output 
///base color
        float4 final_output=base_color_map_value;

        // float normal_smooth_strength = 0.38f;
        // float3 smooth_body_normal = normalize(lerp(vertex_normal, object_radial_normal, normal_smooth_strength));
        // float3 shade_normal = normalize(lerp(pixel_normal, smooth_body_normal, 0.88f));

        float ndotl = dot(vertex_normal, main_light_dir);
        float ndotv = saturate(dot(vertex_normal, view_dir));

///toon shadow
        float shadow_threshold = 0.2f;
        float shadow_softness = 0.018f;
        float toon_light_mask = smoothstep(shadow_threshold - shadow_softness, shadow_threshold + shadow_softness, ndotl);
        float3 shadow_color =base_color_map_value.rgb *0.2f;

        final_output.rgb = lerp(shadow_color, final_output.rgb, toon_light_mask);
///toon light edge
        float toon_light_edge_mask = 1-abs(toon_light_mask*2-1);
        final_output.rgb = lerp(final_output.rgb, 0, toon_light_edge_mask);
///fast sss
        float sss_strength = 0.48f;
        float skin_wrap = 0.5f;
        float3 H =normalize(view_dir - main_light_dir);
        float scatter_power =4.0f;
        float directional_scatter_mask = pow(saturate(dot(pixel_normal,H)),scatter_power);
///rim lighting
        float rim_power = 1.8f;
        float rim_mask = pow(1-saturate(dot(vertex_normal, view_dir)), rim_power);
        
///final blend
        
        // float shadow_depth = GetShadowDepth(ndotl, shadow_threshold, 0.36f);
        // shadow_depth = pow(shadow_depth, 0.72f);

        return rim_mask;
    }
};
TMMDShaderPBRSkin MMDShader;
return MMDShader.OutputColor(Parameters, base_color_map_value, skin_color);
