
#include "/Plugin/Ue5MMDTools/TShaderFunctionLibrary/ColorAdjustment.usf"

// input
// float4 base_color_map_value
struct TMMDShaderPBR
{
    float4 OutputColor(FMaterialPixelParameters material_parameters, float4 base_color_map_value)
    {
        TColorAdjustment color_adjustment;
        float3 base_color = color_adjustment.SafeColor(base_color_map_value.rgb);
        base_color = color_adjustment.AdjustBrightness(base_color, 1.0);
        base_color = color_adjustment.Desaturate(base_color, 1.0);
        base_color = color_adjustment.AdjustContrast(base_color, 1.0);

        return float4(base_color, base_color_map_value.a);
    }
};
TMMDShaderPBR MMDShader;
return MMDShader.OutputColor(Parameters, base_color_map_value);
